### ISSUE TITLE
Demo data

### ISSUE THREAD

**Issue by NaSed** [fjbaldan/DFST#2]
Hi,
Would you please provide a demo data to run the code?
I have problem in running the code and getting meaningful result.

Thank you.

**Comment by fjbaldan** [comment]
Of course, in the following link, you have a script that generates a problem with 4 Classes, where each class corresponds to an ARIMA model of different order and with different coefficients. You only have to indicate the number of time series you want at the start.

https://github.com/fjbaldan/DFST_Experimentation_Sources_Files
